In [1]:
import numpy as np

In [2]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a[:5] = 1
a

array([1, 1, 1, 1, 1, 6, 7, 8, 9])

In [5]:
a[:5] = np.arange(1,6)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = a.copy()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b[:5] = 10
b

array([10, 10, 10, 10, 10,  6,  7,  8,  9])

In [8]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.where(a > 5, 'greater than 5', 'smaller or equal to 5')
b

array(['smaller or equal to 5', 'smaller or equal to 5',
       'smaller or equal to 5', 'smaller or equal to 5',
       'smaller or equal to 5', 'greater than 5', 'greater than 5',
       'greater than 5', 'greater than 5'], dtype='<U21')